language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ikublai/mindblog -f Dockerfile.dev .

script:
  - docker run -e CI=true ikublai/mindblog npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "mindblog"
  env: "mindblog-dev"
  bucket_name: "elasticbeanstalk-us-west-2-263596848727"
  bucket_path: "blog"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


  Mindblog-env.eba-v3imvjaz.us-west-2.elasticbeanstalk.com 